services:
  postgres:
    image: postgres:16
    container_name: expense_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: expense_user
      POSTGRES_PASSWORD: expense_pass
      POSTGRES_DB: expense_db
    ports:
      - "5432:5432"
    volumes:
      - expense_pgdata:/var/lib/postgresql/data

volumes:
  expense_pgdata:
